export const electronicsDb = [
  {
    id: 1,
    title: "Samsung Tv",
    price: "$850.00",
    description: "65' Display • 4K • 120Hz",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 2,
    title: "Canon EOS R155",
    price: "$1,500.00",
    description: "Full Frame Mirrorless Camera",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 3,
    title: "MacBook Pro",
    price: "$1,500.00",
    description: "16' Display • 1TB SSD • 16GB RAM",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 4,
    title: "iPhone 11 Pro",
    price: "$1,000.00",
    description: "256GB • Midnight Green",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 5,
    title: "iPad Pro",
    price: "$1,000.00",
    description: "12.9' Display • 256GB • Space Gray",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 6,
    title: "Mac Pro",
    price: "$5,000.00",
    description: "16' Display • 1TB SSD • 16GB RAM",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
];

export const clothingDb = [
  {
    id: 1,
    title: "Wool Sweater",
    price: "$30.00",
    description: "Lorem ipsum dolor sit amet, consect.",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 2,
    title: "Clothing Outfit",
    price: "$50.00",
    description: "Lorem ipsum dolor sit amet, consect.",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 3,
    title: "Women's Shoes",
    price: "$45.00",
    description: "Lorem ipsum dolor sit amet, consect.",
    location: "Denver, CO",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 4,
    title: "Men's Leather Jacket",
    price: "$120.00",
    description: "Lorem ipsum dolor sit amet, consect.",
    location: "New York, NY",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 5,
    title: "Summer Dress",
    price: "$55.00",
    description: "Lorem ipsum dolor sit amet, consect.",
    location: "Los Angeles, CA",
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 6,
    title: "Running Shoes",
    price: "$70.00",
    description: "Lorem ipsum dolor sit amet, consect.",
    location: "Miami, FL",
    imageUrl: "https://via.placeholder.com/300x200",
  },
];
